version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports: 
      - "2828:2828"
    
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  

    
     








  
#   postgres:
#     image: postgres:alpine
#     container_name: postgres
#     ports:
#       - "5431:5432"
#     environment:
#       POSTGRES_PASSWORD: 1212
#     volumes: 
#       postgres-data: /var/lib/postgresql/data #check again
  
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4
#     ports:
#       - "5888:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: default@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: 1212
# volumes:
#   postgres-data:
#     driver: local
#   #superset-data:


  
  
